### ISSUE TITLE
cli startup using script - supplied wrong dash arg and got NPE

### ISSUE THREAD

**Issue by mdrillin** [Teiid-Designer/komodo#288]
I was running a script from command line - using this 
./vdbbuilder.sh -s ./commandOutput.txt

The -s is wrong (it should have been a -f).

I got this NPE
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:117)
Caused by: java.lang.NullPointerException
	at org.komodo.shell.DefaultKomodoShell.run(DefaultKomodoShell.java:260)
	at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:115)

We need to handle invalid switch gracefully

**Comment by mdrillin** [comment]
#293
