### ISSUE TITLE
NullPointerException running vdbbuilder.bat

### ISSUE THREAD

**Issue by NKame** [Teiid-Designer/komodo#452]
Just built VDBBuilder from a checkout from master. At first run, it crashes with a NullPointerException:
```
d:\vdbbuilder>vdbbuilder.bat
2016-11-23 22:21:17,415 [main] INFO  org.modeshape.common.logging.LogFactory  - SLF4J implementation located in the classpath. It will be used by ModeShape for logging.
Starting engine...
 Started
Starting Local Repository initialization ....2016-11-23 22:21:17,725 [Modeshape Engine Thread] INFO  org.modeshape.jcr.JcrRepository  - ModeShape version 4.5.0.Final
.2016-11-23 22:21:18,067 [Modeshape Engine Thread] INFO  org.infinispan.factories.GlobalComponentRegistry  - ISPN000128: Infinispan version: Infinispan 'Insanely Bad Elf' 7.2.3.Final
2016-11-23 22:21:18,113 [Modeshape Engine Thread] WARN  org.infinispan.transaction.lookup.GenericTransactionManagerLookup  - ISPN000104: Falling back to DummyTransactionManager from Infinispan
2016-11-23 22:21:18,250 [Modeshape Engine Thread] INFO  org.infinispan.persistence.leveldb.LevelDBStore  - ISPN023006: Using pure Java LevelDB implementation: org.iq80.leveldb.impl.Iq80DBFactory
..... Started

Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:137)
Caused by: java.lang.NullPointerException
        at org.komodo.repository.RepositoryImpl.getSession(RepositoryImpl.java:1088)
        at org.komodo.repository.RepositoryImpl.create(RepositoryImpl.java:824)
        at org.komodo.repository.RepositoryImpl.komodoRoot(RepositoryImpl.java:1541)
        at org.komodo.repository.RepositoryImpl.komodoWorkspace(RepositoryImpl.java:1566)
        at org.komodo.ui.DefaultLabelProvider.setRepository(DefaultLabelProvider.java:480)
        at org.komodo.shell.WorkspaceStatusImpl.init(WorkspaceStatusImpl.java:186)
        at org.komodo.shell.WorkspaceStatusImpl.<init>(WorkspaceStatusImpl.java:140)
        at org.komodo.shell.WorkspaceStatusImpl.<init>(WorkspaceStatusImpl.java:126)
        at org.komodo.shell.DefaultKomodoShell.run(DefaultKomodoShell.java:256)
        at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:135)
     Shutting down...
Error during shutdown saving workspace status: null2016-11-23 22:22:10,695 [Thread-0] INFO  org.komodo.spi.logging.KLogger  - Starting shutdown procedure ...
2016-11-23 22:22:10,700 [pool-4-thread-1] ERROR org.modeshape.jcr.ModeShapeEngine  - Failed to shutdown the already-deployed 'Komodo Local Repository' repository prior to redeploying with a new configuration.
java.util.concurrent.ExecutionException: java.lang.IllegalAccessError: already closed
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.modeshape.jcr.ModeShapeEngine.doShutdown(ModeShapeEngine.java:214)
        at org.modeshape.jcr.ModeShapeEngine$1.call(ModeShapeEngine.java:172)
        at org.modeshape.jcr.ModeShapeEngine$1.call(ModeShapeEngine.java:169)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalAccessError: already closed
        at org.mapdb.EngineWrapper$1.commit(EngineWrapper.java:502)
        at org.mapdb.EngineWrapper.commit(EngineWrapper.java:94)
        at org.mapdb.DB.commit(DB.java:1643)
        at org.modeshape.jcr.index.local.LocalIndexProvider.postShutdown(LocalIndexProvider.java:183)
        at org.modeshape.jcr.spi.index.provider.IndexProvider.shutdown(IndexProvider.java:353)
        at org.modeshape.jcr.RepositoryIndexManager.shutdown(RepositoryIndexManager.java:265)
        at org.modeshape.jcr.RepositoryQueryManager.shutdown(RepositoryQueryManager.java:144)
        at org.modeshape.jcr.JcrRepository$RunningState.shutdown(JcrRepository.java:1705)
        at org.modeshape.jcr.JcrRepository.doShutdown(JcrRepository.java:419)
        at org.modeshape.jcr.JcrRepository$1.call(JcrRepository.java:328)
        at org.modeshape.jcr.JcrRepository$1.call(JcrRepository.java:325)
        ... 4 more
2016-11-23 22:22:10,717 [Thread-0] INFO  org.komodo.spi.logging.KLogger  - Shutdown completed.
Exception in thread "Thread-0" java.lang.NullPointerException
        at org.komodo.shell.DefaultKomodoShell.shutdown(DefaultKomodoShell.java:484)
        at org.komodo.shell.DefaultKomodoShell$2.run(DefaultKomodoShell.java:130)
        at java.lang.Thread.run(Thread.java:745)
```

Subsequent runs produce the same result.

**Comment by NKame** [comment]
No more luck with the sh version, I have to check the script
```
$ ./vdbbuilder.sh
cygpath: can't convert empty path
2016-11-23 22:35:08,103 [main] INFO  org.modeshape.common.logging.LogFactory  - SLF4J implementation located in the classpath. It will be used by ModeShape for logging.
Starting engine...
 Started
Starting Local Repository initialization ....2016-11-23 22:35:08,371 [Modeshape Engine Thread] INFO  org.modeshape.jcr.JcrRepository  - ModeShape version 4.5.0.Final
.2016-11-23 22:35:08,656 [Modeshape Engine Thread] INFO  org.infinispan.factories.GlobalComponentRegistry  - ISPN000128: Infinispan version: Infinispan 'Insanely Bad Elf' 7.2.3.Final
2016-11-23 22:35:08,703 [Modeshape Engine Thread] WARN  org.infinispan.transaction.lookup.GenericTransactionManagerLookup  - ISPN000104: Falling back to DummyTransactionManager from Infinispan
2016-11-23 22:35:08,835 [Modeshape Engine Thread] INFO  org.infinispan.persistence.leveldb.LevelDBStore  - ISPN023006: Using pure Java LevelDB implementation: org.iq80.leveldb.impl.Iq80DBFactory
2016-11-23 22:35:08,861 [Modeshape Engine Thread] ERROR org.komodo.spi.logging.KLogger  - Error starting engine
The engine threw an error 'Unable to invoke method public void org.infinispan.persistence.manager.PersistenceManagerImpl.start() on object of type PersistenceManagerImpl'

Exception in thread "main" java.lang.RuntimeException: org.komodo.spi.KException: Unable to create a JCR session
        at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:137)
Caused by: org.komodo.spi.KException: Unable to create a JCR session
        at org.komodo.repository.LocalRepository.createSession(LocalRepository.java:243)
        at org.komodo.repository.LocalRepository.createTransaction(LocalRepository.java:265)
        at org.komodo.shell.WorkspaceStatusImpl.createTransaction(WorkspaceStatusImpl.java:252)
        at org.komodo.shell.WorkspaceStatusImpl.init(WorkspaceStatusImpl.java:170)
        at org.komodo.shell.WorkspaceStatusImpl.<init>(WorkspaceStatusImpl.java:140)
        at org.komodo.shell.WorkspaceStatusImpl.<init>(WorkspaceStatusImpl.java:126)
        at org.komodo.shell.DefaultKomodoShell.run(DefaultKomodoShell.java:256)
        at org.komodo.shell.DefaultKomodoShell.main(DefaultKomodoShell.java:135)

```

**Comment by mdrillin** [comment]
Unfortunately we are behind on maintenance for the command line vdbbuilder on master branch.  You can checkout branch dv-6.3.x if you want to give vdbbuilder a try.

----- Original Message -----

**Comment by NKame** [comment]
Just tried the pre-packaged 0.0.4: starting but failing at reading ddl. I'll drop that version for now :)
