### ISSUE TITLE
Exporting VDB with a model containing a Procedure without a result set ... results in javax.jcr.PathNotFoundException

### ISSUE THREAD

**Issue by blafond** [Teiid-Designer/komodo#68]
A Procedure Result Set child is not always required. However the DdlNodeVisitor.procedure() method assumes it exists.  This results in the exception below.

Caused by: javax.jcr.PathNotFoundException: The child "resultSet" could not be found under "/tko:komodo/tko:workspace/BooksVdb/BooksSource/getBookInfo" in workspace "komodoLocalWorkspace"
	at org.modeshape.jcr.AbstractJcrNode.getNode(AbstractJcrNode.java:800)
	at org.modeshape.jcr.AbstractJcrNode.getNode(AbstractJcrNode.java:1)
	at org.komodo.modeshape.visitor.DdlNodeVisitor.procedure(DdlNodeVisitor.java:818)
	at org.komodo.modeshape.visitor.DdlNodeVisitor.visit(DdlNodeVisitor.java:933)
	... 44 more

**Comment by blafond** [comment]
https://github.com/Teiid-Designer/komodo/pull/73
